# Generated by Django 3.1.4 on 2020-12-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '패스트캠퍼스 게시글', 'verbose_name_plural': '패스트캠퍼스 게시글  '},
        ),
        migrations.RenameField(
            model_name='board',
            old_name='wirter',
            new_name='writer',
        ),
    ]
